accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("", views.accounts, name="accounts"),
    path("<int:category>", views.accounts, name="category"),
    path("time-deposit-ms", views.time_deposit_ms, name="time-deposit-ms"),

]

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import login_user, signup_user, verifyEmail, reset_passowrd
from .view import index, contact

# urls = [
#     path('products/', include('base.urls.product_urls')),
#     path('users/', include('base.urls.user_urls')),
#     path('orders/', include('base.urls.order_urls')),
#     path('air/', include('base.urls.air_urls')),
# ]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('login/', login_user, name='login'),
    path('signup/', signup_user, name='signup'),
    path('reset-password/', reset_passowrd, name='reset_password'),
    path('verify/<str:token>/', verifyEmail, name='verify-email'),
    path('credit-cards/', include('cards.urls')),
    path('personal-loan/', include('loans.urls')),
    path('savings-account/', include('accounts.urls')),
    path('online-brokerage/', include('investment.urls')),
    path('blog/', include('blog.urls')),
    path('rewards/', include('reward.urls')),
    path('FAQs/', include('faqs.urls')),
    path('contact-us/', contact, name='contact'),
    # path('api/v1/', include(urls)),
]

blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path("dining", views.dining, name="dining"),
    # path("<int:category>", views.accounts, name="category"),
]

accounts/models.py
from django.db import models

# Create your models here.


class Account(models.Model):
    title = models.CharField(max_length=30, null=True)
    category = models.CharField(max_length=100, null=True)
    provider = models.ForeignKey(
        "Provider", null=True, on_delete=models.PROTECT, related_name='provider')
    image = models.CharField(max_length=200, null=True)
    disclosure = models.CharField(max_length=30, null=True)
    execlusive = models.CharField(max_length=20, null=True)
    badge_label = models.CharField(max_length=20, null=True)
    badge_primary = models.CharField(max_length=20, null=True)
    snippet = models.TextField(null=True)
    snippet_img = models.CharField(max_length=200, null=True)
    url = models.TextField(null=True)
    promotion = models.TextField(null=True)
    keyfeatures = models.TextField(null=True)
    interestrate = models.TextField(null=True)
    bonusinterestrate = models.TextField(null=True)
    bonuscashrebate = models.TextField(null=True)

    def __str__(self):
        return self.title


class AccountUsp(models.Model):
    dd = models.CharField(max_length=30)
    dt = models.CharField(max_length=200)
    account = models.ForeignKey("Account", related_name='account_usp', on_delete=models.CASCADE)

class Provider(models.Model):
    name = models.CharField(max_length=50)


class Category(models.Model):
    name = models.CharField(max_length=100, null=True)
    slug = models.CharField(max_length=100, null=True)
    doc = models.TextField(null=True)

class HeroSection(models.Model):
    category = models.TextField(null=True)
    url = models.TextField(null=True)

accounts/views.py
from django.shortcuts import render
from django.db.models import Q
from utils.scrape.scrape import get_data
from .models import Account, AccountUsp, Provider, HeroSection

def scrape_account(url):
    accounts = get_data(url)
    # Delete all rows in CardDetail, CardUsp table
    AccountUsp.objects.all().delete()

    for account in accounts:
        row = Account.objects.get(title=account['title'])
        row.image = account['img_src']
        row.disclosure = account['disclosure']
        row.execlusive = account['badge_execlusive']
        row.badge_label = account['badge_label']
        row.badge_primary = account['badge_primary']
        row.snippet = account['snippet']
        row.snippet_img = account['snippet_img']
        row.promotion = account['promotion']
        row.keyfeatures = account['keyFeatures']
        row.interestrate = account['interestRate']
        row.bonusinterestrate = account['bonusInterestRate']
        row.bonuscashrebate = account['bonusCashRebate']
        row.save()

        for usp in account['usp']:
            account_usp = AccountUsp.objects.create(dd=usp['ratio'], dt=usp['text'], account_id=row.id)
            account_usp.save()

# Create your views here.
def get_accounts(category, provider):
    number = Account.objects
    queryset = Account.objects.prefetch_related('account_usp')

    if provider != "0" and provider != None:
        number = number.filter(provider_id=provider)
        queryset = queryset.filter(provider_id=provider)

    if category != None:
        query = str(category) + ','
        number = number.filter(category__contains=query)
        queryset = queryset.filter(category__contains=query)
        
    return number.count(), queryset.all()

def accounts(request, category=None):
    provider = request.GET.get('provider')
    providers = Provider.objects.all()

    # Retrieve all cards joined with their related card details
    number, queryset = get_accounts(category, provider)
    heros = HeroSection.objects.all()

    return render(request, "pages/accounts/accounts.html", 
                  {"Title":"Accounts", "Heros":heros, "MoreIndex":3, "h3":"Compare Best Savings Accounts in Hong Kong", "p":"Search for the best saving accounts to align with your personal saving goals and earn interest on your balance. <br> Start earning extra cash rebate with high deposit interest rate upon opening a savings account. Compare the minimum account balance and savings interest rate to find the one that suits your needs.",
                   "cards": queryset, "number": number, "provider_caption":"Providers", "providers": providers, "prov": provider})

def time_deposit_ms(request):
    accounts = Account.objects.prefetch_related('account_usp').filter(id__in=[1,3,4,6])
    return render(request, "pages/accounts/time-deposit-ms.html",
                  {"accounts":accounts,"tds1": [{"bank":"Citiplus", "annual":"5.4%", "term":"1 month", "mindeposit":"HK$50,000", "mininterest":"HK$219"},
                            {"bank":"HSBC", "annual":"3.4%", "term":"12 months", "mindeposit":"HK$10,000", "mininterest":"HK$340"},
                            {"bank":"Bank of China", "annual":"7%", "term":"7 days", "mindeposit":"HK$50,000", "mininterest":"HK$67.12"},
                            {"bank":"DBS", "annual":"3.0%", "term":"12 months", "mindeposit":"HK$50,000", "mininterest":"HK$1500"},
                            {"bank":"CMB Wing Lung", "annual":"3.85%", "term":"6 months", "mindeposit":"HK$100,000", "mininterest":"HK$1925"},
                            {"bank":"Bank of Communications", "annual":"3.5%", "term":"6 months", "mindeposit":"HK$20,000", "mininterest":"HK$350"},
                            {"bank":"China CITIC Bank (International)", "annual":"3.6%", "term":"3 months", "mindeposit":"HK$10,000", "mininterest":"HK$90"},
                            {"bank":"Standard Chartered Bank", "annual":"3.6%", "term":"12 months", "mindeposit":"HK$10,000", "mininterest":"HK$360"},
                            {"bank":"", "annual":"As of 3rd Apr 2023", "term":"", "mindeposit":"", "mininterest":""},
                            ],
                    "tds2": [{"bank":"FusionBank", "annual":"3.4%", "term":"6 months", "mindeposit":"HK$1", "mininterest":"HK$168.58"},
                            {"bank":"WeLab Bank", "annual":"3.8%", "term":"12 months", "mindeposit":"HK$10", "mininterest":"HK$380"},
                            {"bank":"airstar", "annual":"3.1%", "term":"6 months", "mindeposit":"HK$1,000", "mininterest":"HK$153.82"},
                            {"bank":"ZA Bank", "annual":"3.31%", "term":"12 months", "mindeposit":"HK$1", "mininterest":"HK$331"},
                            {"bank":"", "annual":"As of 3rd Apr 2023", "term":"", "mindeposit":"", "mininterest":""},
                            ],
                    "tds3": [{"bank":"Citibank(Citigold)", "6mon":"2.87%", "6interest":"HK$14,350", "12mon":"N/A", "12interest":"N/A", "additional":""},
                            {"bank":"Hang Seng Bank", "6mon":"4.68%", "6interest":"HK$23,400", "12mon":"N/A", "12interest":"N/A", "additional":"N/A"},
                            {"bank":"ICBC (Asia)", "6mon":"4.6%", "6interest":"HK$23,000", "12mon":"4.6%", "12interest":"HK$46,000", "additional":"N/A"},
                            ],
                            })

templates/pages/accounts/time-deposit-ms.html
{% extends 'base/best_card_base.html' %} 
{% load static %}
{% block hero_section %}
<section class="py-4 bg-grey">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center">
        <a href="{% url 'index' %}" class="text-dark me-3 text-decoration-none">Home</a>
        <a href="#" class="text-dark me-3 text-decoration-none" style="pointer-events:none">
          <i class="fas fa-chevron-right"></i>
        </a>
        <a href="{% url 'accounts:accounts' %}" class="text-dark me-3 text-decoration-none">Savings Account</a>
        <a href="#" class="text-dark me-3 text-decoration-none" style="pointer-events:none">
          <i class="fas fa-chevron-right"></i>
        </a>
        <a href="{% url 'accounts:time-deposit-ms' %}" class="text-dark me-3 text-decoration-none">
          Time Deposit Rates and offer: Best HKD Time Deposit Interest Rates
        </a>
      </div>
      <div class="row mt-4">
        <div class="col-md-8 col-lg-9">
          <h1 class="fs-1">Time Deposit Rates and offer: Best HKD Time Deposit Interest Rates
          </h1>
          <p>Time deposits are considered as stable and safe investments as they give depositors regular and guaranteed
            returns - suitable for investors who prefer low returns with known risks. If you’re considering opening a
            time deposit account and would like to find out about how it works then look no further. This article will
            give you a better understanding of term deposits and how you can benefit from them
          </p>
        </div>
        <div class="col-sm-6 ms-auto col-md-4 col-lg-3">
          <img src="{% static 'img/airport-laungage-card.png' %}" alt="airport-laungage" class="w-100">
        </div>
      </div>
    </div>
  </section>
{% endblock %}
{% block content %}
<section class="my-4">
    <div class="container">
      <!-- ---------text------ -->
      <div class="row mt-5">
        <div class="col-md-4">
          <h3 class="fs-3">Account opening - Documents & Requirements</h3>
        </div>
        <div class="col-md-8">
          <p>If you're a non-resident, you are required to provide a passport and proof of address in your home country.
            You may also be required to provide additional documents, such as letters of employment.</h3>
          </p>
        </div>
      </div>
      <!-- ---------text------ -->
      <div class="row mt-5">
        <div class="col-md-4">
          <h3 class="fs-3">How to open a bank account online?</h3>

        </div>
        <div class="col-md-8">
          <p>
            Even if you are not a permanent resident in Hong Kong, you can still open a bank account in Hong Kong. If
            you are an EU, US or Australian passport holder, the entire process should not be complicated. It can take
            up to 2 weeks to complete the entire account opening process. However, you won’t be able to open a bank
            account remotely because you need to prove your identity as a result of increased amounts of money
            laundering and other illegal activities. You are required to make an appointment and attend a branch in
            person to open your account.
          </p>
        </div>
      </div>
      <!-- ---------text------ -->
      <div class="row mt-5">
        <div class="col-md-4">
          <h3 class="fs-3">Learn more about savings account:</h3>
        </div>
        <div class="col-md-8">
          <p>
            Best Time Deposit Rates in HK
          </p>
        </div>
      </div>
    </div>
  </section>

  <!-- -----------------------
       table 
  ------------------------- -->
  <section class="py-4 card-tbl">
    <div class="container">
      <h2 class="fs-3">Hong Kong Dollar Time Deposit/ Fixed Deposit Rates: Traditional Banks</h2>
      <div class="mt-3 my-shadow">
        <div class="table border-secondary table-responsive">
          <table class="w-100">
            <thead>
              <tr>
                <th class="py-3 px-4">BANK/th>
                <th class="py-3 px-4">ANNUAL INTEREST RATES</th>
                <th class="py-3 px-4">FIXED TERM</th>
                <th class="py-3 px-4">MINIMUM DEPOSIT</th>
                <th class="py-3 px-4">MINIMUM INTEREST PAYMENT</th>
              </tr>
            </thead>
            <tbody>
            {% for td in tds1 %}
              <tr class="">
                <td class="py-3 px-4">{{td.bank}}</a></td>
                <td class="py-3 px-4">{{td.annual}}</td>
                <td class="py-3 px-4">{{td.term}}</td>
                <td class="py-3 px-4">{{td.mindeposit}}</td>
                <td class="py-3 px-4">{{td.mininterest}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </section>
  <!-- =======================
         card descriptions
    ========================= -->
{% for account in accounts %}
  <section class="py-3">
    <div class="container">
      <div class="">
        <h2 class="fs-2">{{ account.title }}</h2>
        <div class="mt-3 row justify-content-center px-0 mt-5 border-bottom border-1 pb-4">
          <div class="col-8 col-sm-6 col-md-3 col-lg-2 d-flex flex-column align-items-center">
            <img src={{account.image}} class="w-100" alt="card-img">
            <a href="#"
              class="d-inline-block text-primary border border-1 text-decoration-none mt-3 mx-auto text-center border-primary rounded-pill px-3 py-2 small">
              <span class="me-2 more-con">More Details</span>
            </a>
          </div>
          <div class="col-md-9 col-lg-8 mt-4 mt-md-0">
            <div class="d-flex flex-wrap">
                {% if account.execlusive %}
                <p class="bg-warning text-dark ex-small me-2">{{account.execlusive}}</p>
                {% endif %} {% if account.badge_label %}
                <p class="blue-bg text-dark ex-small">{{account.badge_label}}</p>
                {% endif %} {% if account.badge_primary %}
                <p class="blue-bg text-dark ex-small">{{account.badge_primary}}</p>
                {% endif %}
              </div>
            <!-- -----------apply-------- -->
            <div class="d-flex flex-wrap align-items-start justify-content-between">
                <div class="row">
                  {% for usp in account.account_usp.all %}
                  <div class="col-6 col-sm-4">
                    <h3 class="fs-5 mb-0 pb-0">{{usp.dd}}</h3>
                    <p class="exx-sm">{{usp.dt}}</p>
                  </div>
                  {% endfor %}
                </div>
                <a role="button" href="{{account.url}}"
                type="submit"
                  class="my-btn d-inline-block text-light text-decoration-none fw-bold small text-capitalize btn-bg py-2 px-3 border-0"
                >
                  Apply Now
              </a>
              </div>
            <!-- --------detail-box-------- -->
            {% if account.snippet %}
            <div class="mt-3 border-start border-warning border-3 card-det-box p-2">
              <div class="row align-items-center">
                <div class="col-md-9 col-lg-10">{{ account.snippet|safe }}</div>
                {% if account.snippet_img %}
                <div class="col-5 col-md-3 col-lg-2 mt-4 mt-md-0">
                  <img
                    src="{{account.snippet_img}}"
                    alt=""
                    class="w-100 rounded-circle"
                  />
                </div>
                {% endif %}
              </div>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
  </section>
{% endfor %}

  <!-- --------banner--------- -->
  <section class="bg-warning py-4">
    <div class="container">
      <div class="row align-items-md-center">
        <div class="col-md-8">
          <h2 class="fs-1">
            Open a savings account to start time deposits now!
          </h2>
        </div>
        <div class="col-md-4 d-flex justify-content-end">
          <a href="{% url 'accounts:accounts' %}" target="_blank"
            class="rounded-3 text-white text-decoration-none fw-md hov-opacity bg-dark py-3 d-inline-block py-2 text-capitalize px-3">
            Compare Saving Account
          </a>
        </div>
      </div>
    </div>
  </section>
  <!-- -----------------------
       table 
  ------------------------- -->
  <section class="py-4 card-tbl">
    <div class="container">
      <h2 class="fs-3">Hong Kong Dollar Time Deposit/ Fixed Deposit Rates: Virtual Banks</h2>
      <div class="mt-3 my-shadow">
        <div class="table border-secondary table-responsive">
          <table class="w-100">
            <thead>
              <tr>
                <th class="py-3 px-4">VIRTUAL BANK</th>
                <th class="py-3 px-4">INTEREST RATES</th>
                <th class="py-3 px-4">FIXED TERM</th>
                <th class="py-3 px-4">MINIMUM DEPOSIT</th>
                <th class="py-3 px-4">MINIMUM INTEREST PAYMENT(CALCULATED BASED ON HK$10,000 DEPOSIT)</th>
              </tr>
            </thead>
            <tbody>
                {% for td in tds2 %}
                <tr class="">
                  <td class="py-3 px-4">{{td.bank}}</a></td>
                  <td class="py-3 px-4">{{td.annual}}</td>
                  <td class="py-3 px-4">{{td.term}}</td>
                  <td class="py-3 px-4">{{td.mindeposit}}</td>
                  <td class="py-3 px-4">{{td.mininterest}}</td>
                </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </section>
  <section class="py-4 card-tbl">
    <div class="container">
      <h2 class="fs-3">Time Deposit Rates of 1 Million HKD or Above</h2>
      <div class="mt-3 my-shadow">
        <div class="table border-secondary table-responsive">
          <table class="w-100">
            <thead>
              <tr>
                <th class="py-3 px-4">BANK</th>
                <th class="py-3 px-4">6-MONTH INTEREST RATE</th>
                <th class="py-3 px-4">INTERESTS</th>
                <th class="py-3 px-4">12-MONTH INTEREST RATE</th>
                <th class="py-3 px-4">INTERESTS</th>
                <th class="py-3 px-4">ADDITIONAL OFFERS</th>
              </tr>
            </thead>
            <tbody>
                {% for td in tds3 %}
                <tr class="">
                  <td class="py-3 px-4">{{td.bank}}</a></td>
                  <td class="py-3 px-4">{{td.6mon}}</td>
                  <td class="py-3 px-4">{{td.6interest}}</td>
                  <td class="py-3 px-4">{{td.12mon}}</td>
                  <td class="py-3 px-4">{{td.12interest}}</td>
                  <td class="py-3 px-4">{{td.additional}}</td>
                </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </section>
  <section>
    <div class="container">
      <div class="row">

        <!-- ----------card-main----- -->
        <div class="mt-5">
          <h2 class="fs-2">
            Why should I consider time deposit?
          </h2>
          <p class="mb-0 pb-0">
            Banks in Hong Kong offer a number of bank accounts such as savings account, current account, time deposits
            accounts for your varying banking needs.
          </p>
          <div class="row mt-4">

            <div class="col-md-6 my-3 col-lg-4 my-lg-2">
              <h3 class="text-dark d-block py-1 text-decoration-none fw-md fs-5 m-0 p-0 lh-1">Low Risk</h3>
              <p class="mb-0 pb-0">
                Savings account provides interest - and lets you withdraw your funds at any time with no penalty.
              </p>
            </div>
            <div class="col-md-6 my-3 col-lg-4 my-lg-2">
              <h3 class="text-dark d-block py-1 text-decoration-none fw-md fs-5 m-0 p-0 lh-1">No extra charge</h3>
              <p class="mb-0 pb-0">
                Current account does not provide account holders with interest, but lets you make payment with cheques.
              </p>
            </div>
            <div class="col-md-6 my-3 col-lg-4 my-lg-2">
              <h3 class="text-dark d-block py-1 text-decoration-none fw-md fs-5 m-0 p-0 lh-1">Low threshold</h3>
              <p class="mb-0 pb-0">
                A fixed or time deposit account gives you a higher rate of interest on the funds you agree to keep at
                the account for a fixed period of time.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}