accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("", views.accounts, name="accounts"),
    path("<int:category>", views.accounts, name="category"),
    path("time-deposit-ms", views.time_deposit_ms, name="time-deposit-ms"),

]

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import login_user, signup_user, verifyEmail, reset_passowrd
from .view import index, contact

# urls = [
#     path('products/', include('base.urls.product_urls')),
#     path('users/', include('base.urls.user_urls')),
#     path('orders/', include('base.urls.order_urls')),
#     path('air/', include('base.urls.air_urls')),
# ]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('login/', login_user, name='login'),
    path('signup/', signup_user, name='signup'),
    path('reset-password/', reset_passowrd, name='reset_password'),
    path('verify/<str:token>/', verifyEmail, name='verify-email'),
    path('credit-cards/', include('cards.urls')),
    path('personal-loan/', include('loans.urls')),
    path('savings-account/', include('accounts.urls')),
    path('online-brokerage/', include('investment.urls')),
    path('blog/', include('blog.urls')),
    path('rewards/', include('reward.urls')),
    path('FAQs/', include('faqs.urls')),
    path('contact-us/', contact, name='contact'),
    # path('api/v1/', include(urls)),
]

blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path("dining", views.dining, name="dining"),
    # path("<int:category>", views.accounts, name="category"),
]

cards/urls.py
from django.urls import path

from . import views

app_name = "cards"
urlpatterns = [
    path("", views.cards, name="cards"),
    path("<int:category>", views.cards, name="category"),
    path("detail/<int:card_id>", views.card_detail, name="detail"),
    path("airport-lounge-free-access-ms", views.airport_lounge_access, name="airport_lounge_access"),
    path("best-asia-miles", views.best_asia_miles, name="best_asia_miles"),    
    path("hotel_reward_booking", views.hotel_reward_booking, name="hotel_reward_booking"),
    path("expat-foreigner-hong-kong-ms", views.expat_foreigner_hong_kong_ms, name="expat_foreigner_hong_kong_ms"),
    path("citibank", views.citibank, name="citibank"),
    path("standard-chartered", views.standard_chartered, name="standard_chartered"),
    path("american-express", views.american_express, name="american_express"),
    path("wewa-unionpay", views.wewa_unionpay, name="wewa_unionpay"),
    path("earnmore-unionpay-card", views.earnmore_unionpay_card, name="earnmore_unionpay_card"),
]

faqs/urls.py
from django.urls import path

from . import views

app_name = "faqs"
urlpatterns = [
    path("", views.faq, name="faqs"),
]

loans/urls.py
from django.urls import path

from . import views

app_name = "loans"
urlpatterns = [
    path("", views.loans, name="loans"),
    path("<int:category>", views.loans, name="category"),
    path("best-standard-chartered-personal-loan-ms", views.scbloans, name="best_scb_personal_loans"),
    path("best-welend-personal-loan-ms", views.welendloans, name="best_welend_personal_loans"),
    path("best-citibank-personal-loan-ms", views.citibank, name="best_citibank_personal_loans"),
    path("best-dbs-personal-loan-ms", views.dbs, name="best_dbs_personal_loan_ms"),
    path("best-quick-loan-in-hong-kong-ms", views.quickloan, name="best_quick_loan_ms"),
    path("low-interest-rate-loan-ms", views.lowinterest, name="low_interest_rate_loan_ms"),
    path("online-loans-ms", views.online, name="online_loans_ms"),
    path("what-is-apr-ms", views.apr, name="apr_ms"),
]

templates/layout/footer.html
{% load static %}
<div class="footer">
  <div class="container">
    <div class="row border-bottom border-1 border-light py-3">
      <div class="col d-sm-flex align-items-center justify-content-between">
        <a href="{% url 'index' %}" class="logo-ftr">
          <img src="{% static 'img/english-logo.png' %}" alt="" class="w-100" />
        </a>
        <div class="d-flex align-items-center py-3">
          <a href="{% url 'index' %}" class="text-dark fs-5 ms-sm-4">About</a>
          <a href="{% url 'contact' %}" class="text-dark fs-5 ms-4"
            >Contact Us</a
          >
          <a href="{% url 'faqs:faqs' %}" class="text-dark fs-5 ms-4">FAQs</a>
        </div>
      </div>
    </div>
    <div class="row mt-4">
      <div class="col-6 col-sm-3">
        <a
          href="{% url 'cards:cards' %}"
          class="text-dark d-block py-1"
          >Credit Cards</a
        >
        <a
          href="{% url 'investment:investments' %}"
          class="text-dark d-block py-1"
          >Investment</a
        >
        <a
          href="{% url 'loans:loans' %}"
          class="text-dark d-block py-1"
          >Loans</a
        >
      </div>
      <div class="col-6 col-sm-3">
        <a href="{% url 'blog:dining' %}" class="text-dark d-block py-1"
          >Blog</a
        >
        <a
          href="{% url 'accounts:accounts' %}"
          class="text-dark d-block py-1"
          >Accounts</a
        >
      </div>
    </div>
    <!-- --------copyright----- -->
    <div class="row mt-4">
      <p class="text-center text-dark small mt-3">
        © 2009-2023 Crediboo. All rights reserved. Use of this site constitutes
        acceptance of our Terms of Use and Privacy Policy.
      </p>
    </div>
  </div>
</div>
<!-- Bootstrap 5 JS CDN (Optional) -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Custom JS -->
<script src="{% static 'js/main.js' %}"></script>
<!-- ------slick-js--- -->
<!-- <script type="text/javascript" src="https://code.jquery.com/jquery-3.6.0.min.js"></script> -->
<script type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>

templates/layout/head.html
{% load static %} {% block head %}
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Crediboo || {{Title}}</title>
  <link rel="icon" type="image/x-icon" href="{% static 'img/yellowbg-2.png' %}"/>
  <!-- ----jquery-ui----- -->
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css"
  />
  <!-- Bootstrap 5 CSS CDN -->
  <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
  />
  <!-- Font Awesome CDN -->
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
  />
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'css/main.css' %}" />
  <!-- ----slider css-- -->
  <link
    rel="stylesheet"
    type="text/css"
    href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css"
  />
  <!-- jQuery CDN -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
</head>
{% endblock %}

templates/layout/head_section.html
{% block head_section %} {% load static %}
<section class="py-4 bg-grey">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center">
      <a href="{% url 'index' %}" class="text-dark me-3 text-decoration-none"
        >Home</a
      >
      <a
        href="#"
        class="text-dark me-3 text-decoration-none"
        style="pointer-events: none"
      >
        <i class="fas fa-chevron-right"></i>
      </a>
      <a href="{{url}}" class="text-dark me-3 text-decoration-none"
        >{{section}}</a
      >
      <a
        href="#"
        class="text-dark me-3 text-decoration-none"
        style="pointer-events: none"
      >
        <i class="fas fa-chevron-right"></i>
      </a>
      <a href="#" class="text-dark me-3 text-decoration-none">{{broadcrump}}</a>
    </div>
    <div class="row mt-4">
      <div class="col-md-8 col-lg-9">
        <h1 class="fs-1">{{title}}</h1>
        <p>{{description}}</p>
      </div>
      <div class="col-sm-6 ms-auto col-md-4 col-lg-3">
        <img
          src="{% static 'img/airport-laungage-card.png' %}"
          alt="airport-laungage"
          class="w-100"
        />
      </div>
    </div>
  </div>
</section>
{% if subtitle %}
<section class="py-4 blue-bg">
  <div class="container">
    <h2 class="fs-5 text-dark">{{subtitle}}</h2>
    <p class="mt-4 mb-0 pb-0 text-dark">{{ sub_desc}}</p>
    <div class="mt-2 row">
      {% for category in categories %} {% if forloop.counter <= 3 %}
      <div class="col-sm-6 my-2 my-md-0 col-md-4 mb-2">
        <a
          href="#{{category.link}}"
          class="d-block text-decoration-none text-dark h-100"
        >
          <div class="bg-white h-100 py-3 px-3">
            <h3 class="fs-6 fw-normal">{{category.category|upper}}</h3>
            <h3 class="fs-6 fw-md">{{category.desc}}</h3>
          </div>
        </a>
      </div>
      {% endif %} {% endfor %}
    </div>
    {% if categories|length > 3 %}
    <div class="mt-2 row">
      {% for category in categories %} {% if forloop.counter > 3 %}
      <div class="col-sm-6 my-2 my-md-0 col-md-4 mb-2">
        <a
          href="#{{category.link}}"
          class="d-block text-decoration-none text-dark h-100"
        >
          <div class="bg-white h-100 py-3 px-3">
            <h3 class="fs-6 fw-normal">{{category.category|upper}}</h3>
            <h3 class="fs-6 fw-md">{{category.desc}}</h3>
          </div>
        </a>
      </div>
      {% endif %} {% endfor %}
    </div>
    {% endif %}
  </div>
</section>
{% endif %} {% endblock %}

templates/layout/sidebar.html
{% block sidebar %}
<div class="col-sm-4 col-lg-3">
  <h6 class="text-capitalize fs-6">Refine your results</h6>
  {% if filter_caption != None %}
  <h2 class="mt-3 small">{{filter_caption}}</h2>
  <div>
    <form action="" class="d-flex flex-sm-column flex-wrap">
      {% for filter in filters %}
      {% if feature_caption != None and filter.id < 3 or feature_caption == None %}
      <div class="d-flex align-items-start me-2 me-sm-0">
        {% if filter.id|stringformat:"d" in assoc %}
        <input class="me-2 mt-2 association" id="ass-{{filter.id}}" type="checkbox" name="association" value="{{filter.id}}" checked/>
        {% else %}
        <input class="me-2 mt-2 association" id="ass-{{filter.id}}" type="checkbox" name="association" value="{{filter.id}}" />
        {% endif %}
        <label for="ass-{{filter.id}}">{{filter.name}}</label>
      </div>
      {% endif %}
      {% endfor %}
      {% if feature_caption == None %}
      <div class="d-block w-100">
        <button
          type="reset"
          class="text-primary small border-0 bg-transparent px-0 mt-sm-2"
        >
          Reset Filter
        </button>
      </div>
      {% endif %}
    </form>
  </div>
  {% endif %}
  {% if feature_caption != None %}
  <h2 class="mt-3 small">{{feature_caption}}</h2>
  <div>
    <form action="" class="d-flex flex-sm-column flex-wrap">
      <div class="d-flex align-items-start me-2 me-sm-0">
        {% if 3|stringformat:"d" in assoc %}
        <input class="me-2 mt-2 association" id="ass-3" type="checkbox" name="association" value="3" checked/>
        {% else %}
        <input class="me-2 mt-2 association" id="ass-3" type="checkbox" name="association" value="3" />
        {% endif %}
        <label for="ass-3">No Min.Funding</label>
      </div>
    </form>
  </div>
  {% endif %}
  <h2 class="mt-3 small">{{provider_caption}}</h2>
  <div>
    <form action="" class="d-flex flex-sm-column flex-wrap">
      <div class="d-flex align-items-start me-2 me-sm-0">
        {% if prov|add:"0" == 0 or prov == None %}
        <input
          class="me-2 mt-2 provider"
          name="provider0"
          type="radio"
          id="p0"
          checked
          value="0"
        />
        {% else %}
        <input
          class="me-2 mt-2 provider"
          name="provider0"
          type="radio"
          id="p0"
          value="0"
        />
        {% endif %}
        <label for="p0">All {{provider_caption}}</label>
      </div>
      {% for provider in providers %}
      <div class="d-flex align-items-start me-2 me-sm-0">
        {% if prov|add:"0" == provider.id|add:"0" %}
        <input
          class="me-2 mt-2 provider"
          name="provider{{provider.id}}"
          type="radio"
          checked
          id="p{{provider.id}}"
          value="{{provider.id}}"
        />
        <label for="p{{provider.id}}">{{provider.name}}</label>
        {% else %}
        <input
          class="me-2 mt-2 provider"
          name="provider{{provider.id}}"
          type="radio"
          id="p{{provider.id}}"
          value="{{provider.id}}"
        />
        <label for="p{{provider.id}}">{{provider.name}}</label>
        {% endif %}
      </div>
      {% endfor %}
    </form>
  </div>

</div>
{% endblock %}

templates/layout/translate.html
<div class="main-p-translate">
  <div id="google_element" class="blue-dark-bg"></div>
  <script src="http://translate.google.com/translate_a/element.js?cb=loadGoogleTranslate"></script>
  <script>
    function loadGoogleTranslate() {
      new google.translate.TranslateElement(
        {
          includedLanguages: "en,zh-CN,zh-TW",
          layout: google.translate.TranslateElement.InlineLayout.HORIZONTAL,
        },
        "google_element"
      );

      // Add event listener to the Google Translate dropdown
      var googleTranslateElement = document.querySelector(".goog-te-combo");
      googleTranslateElement.addEventListener("change", function () {
        var selectedLanguage = this.value;
        showLogo(selectedLanguage);
      });
    }
  </script>
</div>